#!/usr/bin/env python3
"""
Generate extra_model_paths.yaml for ComfyUI

This script generates the ComfyUI extra_model_paths.yaml configuration file
that tells ComfyUI where to find models on the network volume.

The configuration enables:
- Models stored on network volume (/workspace/models)
- No need to sync models to container
- Persistent models across container restarts
"""

import os
import yaml
from pathlib import Path

DEFAULT_CONFIG = {
    "workspace_models": {
        "base_path": "/workspace/models",
        "checkpoints": "checkpoints/",
        "diffusion_models": "diffusion_models/",
        "text_encoders": "text_encoders/",
        "vae": "vae/",
        "clip_vision": "clip_vision/",
        "loras": "loras/",
        "audio_encoders": "audio_encoders/",
        "upscale_models": "upscale_models/",
        "controlnet": "controlnet/",
        "embeddings": "embeddings/",
        "TTS": "TTS/",
        "custom_nodes": "custom_nodes/",
    },
    "output": {
        "base_path": "/workspace",
        "output": "output/",
    }
}

def generate_extra_model_paths(output_path: str = None, custom_base_path: str = None):
    """
    Generate extra_model_paths.yaml for ComfyUI

    Args:
        output_path: Path to write the YAML file (default: /app/comfyui/extra_model_paths.yaml)
        custom_base_path: Custom base path for models (default: /workspace/models)
    """
    if output_path is None:
        output_path = os.environ.get(
            "EXTRA_MODEL_PATHS_CONFIG",
            "/app/comfyui/extra_model_paths.yaml"
        )

    if custom_base_path is None:
        custom_base_path = os.environ.get(
            "MODELS_PATH",
            "/workspace/models"
        )

    # Create config with custom base path
    config = DEFAULT_CONFIG.copy()
    config["workspace_models"]["base_path"] = custom_base_path

    # Ensure output directory exists
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # Write YAML config
    with open(output_file, 'w') as f:
        f.write("# ComfyUI extra_model_paths.yaml\n")
        f.write("# Generated by generate_extra_paths.py\n")
        f.write("# Models are stored on the network volume for persistence\n\n")
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)

    print(f"[INFO] Generated extra_model_paths.yaml at {output_path}")
    print(f"[INFO] Models base path: {custom_base_path}")

    return output_path

def create_model_directories(base_path: str = None):
    """
    Create model directories if they don't exist

    Args:
        base_path: Base path for models (default: /workspace/models)
    """
    if base_path is None:
        base_path = os.environ.get("MODELS_PATH", "/workspace/models")

    model_dirs = [
        "checkpoints",
        "diffusion_models",
        "text_encoders",
        "vae",
        "clip_vision",
        "loras",
        "audio_encoders",
        "upscale_models",
        "controlnet",
        "embeddings",
        "TTS",
        "custom_nodes",
    ]

    base = Path(base_path)
    created = []

    for dir_name in model_dirs:
        dir_path = base / dir_name
        if not dir_path.exists():
            dir_path.mkdir(parents=True, exist_ok=True)
            created.append(dir_name)

    if created:
        print(f"[INFO] Created model directories: {', '.join(created)}")
    else:
        print(f"[INFO] All model directories already exist")

def validate_model_paths(config_path: str = None):
    """
    Validate that extra_model_paths.yaml exists and is valid

    Args:
        config_path: Path to the YAML file

    Returns:
        bool: True if valid, False otherwise
    """
    if config_path is None:
        config_path = "/app/comfyui/extra_model_paths.yaml"

    config_file = Path(config_path)

    if not config_file.exists():
        print(f"[WARN] extra_model_paths.yaml not found at {config_path}")
        return False

    try:
        with open(config_file, 'r') as f:
            config = yaml.safe_load(f)

        if not config:
            print(f"[WARN] extra_model_paths.yaml is empty")
            return False

        # Check for required sections
        if "workspace_models" not in config:
            print(f"[WARN] workspace_models section not found in config")
            return False

        base_path = config["workspace_models"].get("base_path")
        if not base_path:
            print(f"[WARN] base_path not defined in workspace_models")
            return False

        if not Path(base_path).exists():
            print(f"[WARN] Models base path does not exist: {base_path}")
            return False

        print(f"[INFO] extra_model_paths.yaml is valid")
        print(f"[INFO] Models base path: {base_path}")
        return True

    except yaml.YAMLError as e:
        print(f"[ERROR] Failed to parse extra_model_paths.yaml: {e}")
        return False

def main():
    """Main entry point"""
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate ComfyUI extra_model_paths.yaml"
    )
    parser.add_argument(
        "--output", "-o",
        default="/app/comfyui/extra_model_paths.yaml",
        help="Output path for the YAML file"
    )
    parser.add_argument(
        "--base-path", "-b",
        default="/workspace/models",
        help="Base path for models"
    )
    parser.add_argument(
        "--create-dirs",
        action="store_true",
        help="Create model directories if they don't exist"
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Validate existing configuration"
    )

    args = parser.parse_args()

    if args.validate:
        success = validate_model_paths(args.output)
        exit(0 if success else 1)

    # Generate the config
    generate_extra_model_paths(args.output, args.base_path)

    # Create directories if requested
    if args.create_dirs:
        create_model_directories(args.base_path)

    # Validate the generated config
    validate_model_paths(args.output)

if __name__ == "__main__":
    main()
